### ISSUE TITLE
adding .draggable() functionality to clones

### ISSUE THREAD

**Issue by lionsdwarf** [lionsdwarf/art-victim#1]
@WilliamfShaw @bigtone1284 

draggable (and sortable/resizable) functionality is essential for manipulating image layouts for my card constructor app. if i apply .draggable() to an image from my index.html, it works. but there's another layer of complexity this functionality will not so far transcend, specifically regarding handlebars objects and clones of handelbars dom objects. 

my library of images appear on dom via handlebars. to then select an image to manipulate, I use a clone of that handlebars object so that multiple copies of the same image can be used/manipulated. however, .draggable() works on none of the above. 

i discovered that .draggable() adds two classes to an image: "ui-draggable" and "ui-draggable handle". accordingly, i tried hard-coding these classes onto the objects but neither the handlebars-rendered objects nor the clones had any draggable functionality thereafter. 

the problem might be that both handlebars objects and the clone objects are appended to their respective points on the dom. perhaps this appending is conflicting with the draggability, but i tried to simply create a clone without appending it anywhere, but not surprisingly, the clone didn't appear on the dom. 

the code for cloning is here : 

```
 renderToCanvas: function(graphicModel) {
    var clone = this.cloneNode(true);
    $('#canvas').append(clone);
    // addSortable(graphicModel);
  }
```

here's the hard-coded index.html img that is draggable:

```
 <img id="Snoop" class="draggable" src="/graphics/music/snoop_murder_wt_case.png" alt="snooptest">
```

whereas the handlebars template that renders img to dom and is also the source for cloning is here:

```
  <template id="graphic-template">
      <img id="{{name}}" class= "draggable ui-draggable ui-draggable-handle" src="{{url}}" alt="{{name}}" >
  </template>
```

Pls halp!

**Comment by bigtone1284** [comment]
Still having some issues with this?

**Comment by lionsdwarf** [comment]
Yessir. Im on 3 in a cubbie hole in the back
